name: CI

on:
  push:
  workflow_dispatch:
    inputs:
      ngrok_auth_token:
        description: 'Ngrok Auth Token'
        required: true
        type: string

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Download
      run: Invoke-WebRequest https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-windows-amd64.zip -OutFile ngrok.zip

    - name: Extract
      run: Expand-Archive ngrok.zip

    - name: Auth
      run: .\ngrok\ngrok.exe authtoken $Env:NGROK_AUTH_TOKEN
      env:
        NGROK_AUTH_TOKEN: ${{ github.event.inputs.ngrok_auth_token }}

    - name: Enable TS
      run: Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name "fDenyTSConnections" -Value 0

    - name: Enable Firewall Rule
      run: Enable-NetFirewallRule -DisplayGroup "Remote Desktop"

    - name: Enable User Authentication
      run: Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -Name "UserAuthentication" -Value 1
    - name: Create a local user account
      run: New-LocalUser -Name "$Env:USERNAME" -Password (ConvertTo-SecureString -AsPlainText "$Env:PASS" -Force)
      env:
        USERNAME: ${{ secrets.USERNAME }}
        PASS: ${{ secrets.PASS }}
    - name: Add LocalGroupMember
      run: Add-LocalGroupMember -Group "Administrators" -Member "$Env:USERNAME"
      env:
        USERNAME: ${{ secrets.USERNAME }}
    - name: Create PowerShell script
      run: |
        $scriptContent = @"
        \$result = Invoke-WebRequest -Uri http://localhost:4040/api/tunnels -UseBasicParsing | ConvertFrom-Json | Select-Object -ExpandProperty tunnels | Select-Object -First 1 | Select-Object -ExpandProperty public_url
        Invoke-RestMethod -Uri "`$Env:domain`" -Method Post -ContentType "application/x-www-form-urlencoded" -Body @{result = \$result}
        Write-Host "Task completed"
        "@
        # Tạo tệp PowerShell với nội dung tại ổ D:
        $filePath = "D:\delayed_script.ps1"
        [System.IO.File]::WriteAllText($filePath, $scriptContent)
        Write-Host "PowerShell script created at $filePath"
      env:
        domain: ${{ secrets.domain }}
    - name: Create Tunnel
      run: .\ngrok\ngrok.exe tcp 3389 --region=us-cal-1
